export const projects = [
  {
    id: 1,
    name: "Koos Languages",
    client: "Koos-End Language Centre",
    role: "Full-stack development",
    description:
      "A responsive language learning website designed to offer an accessible platform for learners at various skill levels. The site features interactive language resources, practice materials, and tools aimed at enhancing language proficiency. With a mobile-friendly layout and user-focused design, Koos Languages makes language learning engaging and convenient.",
    overview:
      "A user-friendly, responsive platform that simplifies language learning through a clean interface and structured content.",
    intent:
      "Designed with accessibility at its core to support learners across various devices and backgrounds.",
    goal: "Focused on simplicity, clarity, and multilingual support to enhance engagement and ease of use.",
    stack: ["React", "Nodejs", "Figma", "Styled Component"],
    status: "Published",
    year: "Jul 2024",
    images: ["/src/assets/img/koos/img.png"],
    gitHubLink: "",
    externalLink: "",
    type: "web",
  },
  {
    id: 2,
    name: "Walleth",
    client: "Koos-End Language Centre",
    role: "Web3 Development",
    description:
      "Walleth is a high-performance, multi-chain, and multi-currency cryptocurrency wallet designed with advanced security architecture. Built for speed, reliability, and seamless user experience, it empowers users to manage digital assets across diverse blockchain networks effortlessly.",
    overview:
      "A secure, scalable crypto wallet solution built for managing digital assets across multiple chains.",
    intent:
      "Engineered for speed and performance with real-time data sync and encrypted asset protection.",
    goal: "UX-first design for effortless transaction handling, wallet switching, and multi-chain operations.",
    stack: ["React", "Web3", "Figma", "Tailwind", "Ethersjs"],
    status: "Published",
    year: "Dec 2024",
    images: ["/src/assets/img/walleth/home2.png"],
    gitHubLink: "",
    externalLink: "",
    type: "web",
  },
  {
    id: 3,
    name: "Arie Classic",
    client: "Koos-End Language Centre",
    role: "UX/UI Design, Web Development",
    description:
      "Arie Classic is a sleek, responsive fashion website designed for style enthusiasts seeking refined digital experiences. It blends aesthetics with functionality, offering visitors a smooth journey through curated collections tailored to diverse fashion preferences.",
    overview:
      "A minimal yet elegant fashion platform tailored for users with diverse aesthetic preferences.",
    intent:
      "Responsive layout and rich visuals bring the brand’s essence to life across all screen sizes.",
    goal: "Combines editorial style with intuitive navigation to create a compelling digital brand presence.",
    stack: ["React", "Tailwind", "Figma"],
    status: "In development",
    year: "Oct 2024",
    images: ["/src/assets/img/arie/img1.png"],
    gitHubLink: "",
    externalLink: "",
    type: "design",
  },
];

export const otherProjects = [
  {
    id: 1,
    name: "Forkify App",
    type: "Web development",
    overview:
      "A recipe application that allows users to search for recipes based on the Forkify API. Users can upload custom recipes and bookmark favorite recipes",
    intent: "A recipe search application",
    stack: ["JavaScript", "HTML", "CSS", "Netlify"],
    status: "In development",
    year: "Mar 2022",
    images: ["/src/assets/img/others/forkify.png"],
    goal: "",
    client: "",
    role: "",
    description: "",
    gitHubLink: "",
    externalLink: "",
  },
  {
    id: 2,
    name: "Tindog",
    type: "Web development",
    overview:
      "Social dating website, exclusively designed for our four-legged friends, to find a playmate, a soulmate, or simply a canine companion.",
    intent: "Social dating website for dogs.",
    stack: ["React", "Bootstrap", "Figma"],
    status: "Published",
    year: "Jul 2023",
    images: ["/src/assets/img/others/sample.png"],
    goal: "",
    client: "",
    role: "",
    description: "",
    gitHubLink: "",
    externalLink: "",
  },
  {
    id: 3,
    name: "Secrets",
    type: "Web development",
    overview:
      "An app that allows users to annonymously share and view others secrets after login. Includes login with Google/Facebook options.",
    intent: "Annonymously share secrets",
    stack: ["Nodejs", "MongoDB", "EJS"],
    status: "Published",
    year: "Aug 2023",
    images: ["/src/assets/img/others/sample.png"],
    goal: "",
    client: "",
    role: "",
    description: "",
    gitHubLink: "",
    externalLink: "",
  },
  {
    id: 4,
    name: "Task Planner",
    type: "Web development",
    overview:
      "A modern to-do task planner built with Node.js, Express nd Bootstrap.",
    intent: "A modern to-do task planner",
    stack: ["Nodejs", "JavaScript", "Bootstrap"],
    status: "Published",
    year: "Aug 2023",
    images: ["/src/assets/img/others/sample.png"],
    goal: "",
    client: "",
    role: "",
    description: "",
    gitHubLink: "",
    externalLink: "",
  },
  {
    id: 5,
    name: "Simon Game",
    type: "Web development",
    overview:
      "A game to improve short-term memory skill based on the invention of Ralph Baer and Howard Morrison",
    intent: "A short-term memory skill game",
    stack: ["HTML5", "CSS3", "JQuery"],
    status: "Published",
    year: "May 2023",
    images: ["/src/assets/img/others/sample.png"],
    goal: "",
    client: "",
    role: "",
    description: "",
    gitHubLink: "",
    externalLink: "",
  },
  {
    id: 6,
    name: "Calculator App",
    type: "Software development",
    overview:
      "A calculator app created as my first Java project. This app is inspired by the Apple iPhone calculator app. The GUI is built with JavaFX",
    intent: "A short-term memory skill game",
    stack: ["Java", "JavaFX"],
    status: "Published",
    year: "May 2023",
    images: ["/src/assets/img/others/sample.png"],
    goal: "",
    client: "",
    role: "",
    description: "",
    gitHubLink: "",
    externalLink: "",
  },
];
